import CoreGraphics

// Auto-generated by tools/parse_field_coords.py
// Coordinates are scaled to 640×400 (perspective-corrected crop space).

enum CardFieldId: String, CaseIterable {
    case lastName
    case firstName
    case patronymic
    case gender
    case nationality
    case birthDate
    case docNumber
    case expiryDate
    case birthPlace
    case issuedBy
    case issueDate
    case personalNumber
    case mrz
}

struct CardFieldRect {
    let id: CardFieldId
    let name: String
    let rect: CGRect  // in 640×400 crop space
}

/// Key: CardVersion rawValue
/// 0=Back2008, 1=Back2017, 2=Back2025, 3=Front2008, 4=Front2017, 5=Front2025
let cardFieldCoords: [Int: [CardFieldRect]] = [
    0: [  // Back2008
        CardFieldRect(id: .expiryDate, name: "expiry_date", rect: CGRect(x: 17, y: 200, width: 389, height: 16)),
        CardFieldRect(id: .issuedBy, name: "issued_by", rect: CGRect(x: 17, y: 237, width: 389, height: 16)),
        CardFieldRect(id: .issueDate, name: "issue_date", rect: CGRect(x: 17, y: 144, width: 389, height: 16)),
        CardFieldRect(id: .mrz, name: "mrz", rect: CGRect(x: 23, y: 277, width: 601, height: 90))
    ],
    1: [  // Back2017
        CardFieldRect(id: .nationality, name: "nationality", rect: CGRect(x: 172, y: 190, width: 243, height: 19)),
        CardFieldRect(id: .docNumber, name: "doc_number", rect: CGRect(x: 450, y: 156, width: 128, height: 19)),
        CardFieldRect(id: .birthPlace, name: "birth_place", rect: CGRect(x: 172, y: 48, width: 243, height: 43)),
        CardFieldRect(id: .issuedBy, name: "issued_by", rect: CGRect(x: 172, y: 114, width: 243, height: 19)),
        CardFieldRect(id: .issueDate, name: "issue_date", rect: CGRect(x: 172, y: 154, width: 243, height: 19)),
        CardFieldRect(id: .personalNumber, name: "personal_number", rect: CGRect(x: 417, y: 100, width: 192, height: 19)),
        CardFieldRect(id: .mrz, name: "mrz", rect: CGRect(x: 21, y: 274, width: 589, height: 93))
    ],
    2: [  // Back2025
        CardFieldRect(id: .nationality, name: "nationality", rect: CGRect(x: 439, y: 128, width: 180, height: 24)),
        CardFieldRect(id: .birthPlace, name: "birth_place", rect: CGRect(x: 190, y: 45, width: 207, height: 43)),
        CardFieldRect(id: .issuedBy, name: "issued_by", rect: CGRect(x: 190, y: 120, width: 180, height: 24)),
        CardFieldRect(id: .issueDate, name: "issue_date", rect: CGRect(x: 192, y: 173, width: 203, height: 35)),
        CardFieldRect(id: .personalNumber, name: "personal_number", rect: CGRect(x: 439, y: 70, width: 178, height: 24)),
        CardFieldRect(id: .mrz, name: "mrz", rect: CGRect(x: 30, y: 273, width: 586, height: 90))
    ],
    3: [  // Front2008
        CardFieldRect(id: .lastName, name: "last_name", rect: CGRect(x: 224, y: 144, width: 377, height: 16)),
        CardFieldRect(id: .firstName, name: "first_name", rect: CGRect(x: 224, y: 184, width: 377, height: 16)),
        CardFieldRect(id: .patronymic, name: "patronymic", rect: CGRect(x: 226, y: 223, width: 377, height: 16)),
        CardFieldRect(id: .gender, name: "gender", rect: CGRect(x: 459, y: 265, width: 148, height: 16)),
        CardFieldRect(id: .nationality, name: "nationality", rect: CGRect(x: 228, y: 348, width: 162, height: 16)),
        CardFieldRect(id: .birthDate, name: "birth_date", rect: CGRect(x: 226, y: 265, width: 164, height: 16)),
        CardFieldRect(id: .docNumber, name: "doc_number", rect: CGRect(x: 70, y: 330, width: 132, height: 16)),
        CardFieldRect(id: .birthPlace, name: "birth_place", rect: CGRect(x: 228, y: 306, width: 176, height: 16)),
        CardFieldRect(id: .personalNumber, name: "personal_number", rect: CGRect(x: 410, y: 364, width: 198, height: 16))
    ],
    4: [  // Front2017
        CardFieldRect(id: .lastName, name: "last_name", rect: CGRect(x: 254, y: 93, width: 358, height: 42)),
        CardFieldRect(id: .firstName, name: "first_name", rect: CGRect(x: 254, y: 144, width: 358, height: 42)),
        CardFieldRect(id: .patronymic, name: "patronymic", rect: CGRect(x: 254, y: 193, width: 358, height: 23)),
        CardFieldRect(id: .gender, name: "gender", rect: CGRect(x: 254, y: 227, width: 358, height: 23)),
        CardFieldRect(id: .nationality, name: "nationality", rect: CGRect(x: 252, y: 258, width: 358, height: 23)),
        CardFieldRect(id: .birthDate, name: "birth_date", rect: CGRect(x: 254, y: 293, width: 117, height: 23)),
        CardFieldRect(id: .docNumber, name: "doc_number", rect: CGRect(x: 450, y: 303, width: 117, height: 23)),
        CardFieldRect(id: .expiryDate, name: "expiry_date", rect: CGRect(x: 450, y: 346, width: 119, height: 23))
    ],
    5: [  // Front2025
        CardFieldRect(id: .lastName, name: "last_name", rect: CGRect(x: 230, y: 102, width: 325, height: 35)),
        CardFieldRect(id: .firstName, name: "first_name", rect: CGRect(x: 230, y: 151, width: 325, height: 35)),
        CardFieldRect(id: .patronymic, name: "patronymic", rect: CGRect(x: 230, y: 200, width: 325, height: 18)),
        CardFieldRect(id: .gender, name: "gender", rect: CGRect(x: 230, y: 235, width: 61, height: 18)),
        CardFieldRect(id: .nationality, name: "nationality", rect: CGRect(x: 230, y: 269, width: 278, height: 22)),
        CardFieldRect(id: .birthDate, name: "birth_date", rect: CGRect(x: 230, y: 306, width: 110, height: 18)),
        CardFieldRect(id: .docNumber, name: "doc_number", rect: CGRect(x: 437, y: 320, width: 118, height: 18)),
        CardFieldRect(id: .expiryDate, name: "expiry_date", rect: CGRect(x: 437, y: 369, width: 124, height: 18))
    ]
]
