// swift-tools-version: 5.9
// Generated by scripts/release_ios.sh for v2.2.1 — do not hand-edit;
// re-run the packaging script to regenerate.
import PackageDescription

let package = Package(
    name: "Mergen",
    platforms: [.iOS(.v16)],
    products: [
        // One-line client integration: add "Mergen" as a package dependency and
        // this product as a target dependency. Both the binary framework and the
        // model-asset bundle come with it — no linkerSettings on the client side
        // (every dependency is linked inside the binary as of 2.2.0).
        .library(
            name: "Mergen",
            targets: ["Mergen", "MergenResources"]
        ),
        // Debug/QA diagnostics module. Add to QA targets only — writes PII to os_log.
        // See docs/DIAGNOSTICS.md for integration guidance.
        .library(
            name: "MergenDebugger",
            targets: ["MergenDebugger"]
        ),
    ],
    targets: [
        // Precompiled Swift wrapper (BUILD_LIBRARY_FOR_DISTRIBUTION, mh_dylib),
        // with the C++ core + OpenCV + ONNX Runtime + OpenSSL linked statically
        // inside. Resolved as a zip download from the GitHub Release for this
        // tag and verified against the checksum below.
        .binaryTarget(
            name: "Mergen",
            path: "MergenSwift.xcframework"
        ),
        // Model assets — a source target, because a binaryTarget cannot carry
        // SPM resources, and embedding them per-slice would duplicate ~73 MB
        // across device+simulator. MergenEngine.findResourceBundle() locates the
        // generated bundle at runtime; MergenEngine.setResourceBundle(_:) overrides.
        .target(
            name: "MergenResources",
            path: "Sources/MergenResources",
            resources: [
                .copy("m12.onnx.encrypted"),
                .copy("m13.onnx.encrypted"),
                .copy("m14.onnx.encrypted"),
                .copy("m15.onnx.encrypted"),
                .copy("m4.onnx.encrypted"),
                .copy("m4_dict.txt"),
                .copy("m5.ort.encrypted"),
                .copy("m7.onnx.encrypted"),
                .copy("m7_dict.txt"),
            ]
        ),
        // Debug/QA module — PII diagnostics (logging/formatting only, no
        // algorithms). Dependency is ONE-WAY: MergenDebugger → Mergen, never the
        // reverse. Clients: add to a separate QA target. See docs/DIAGNOSTICS.md.
        .target(
            name: "MergenDebugger",
            dependencies: ["Mergen"],
            path: "Sources/MergenDebugger"
        ),
    ]
)
