// swift-tools-version: 5.9
// Generated by scripts/release_ios.sh for v2.1.0 — do not hand-edit;
// re-run the packaging script to regenerate.
import PackageDescription

let package = Package(
    name: "Mergen",
    platforms: [.iOS(.v16)],
    products: [
        .library(
            name: "Mergen",
            targets: ["Mergen"]
        ),
    ],
    targets: [
        // Binary dependencies — resolved as zip downloads from the GitHub
        // Release for this tag, verified against the checksums below.
        .binaryTarget(
            name: "MergenCore",
            url: "https://github.com/DanielPHP01/MergenSDK-iOS/releases/download/v2.1.0/Mergen.xcframework.zip",
            checksum: "3fe6b393df8fb22bb14d2edfb0115496cb121506498b6d4fc28658044398da1e"
        ),
        .binaryTarget(
            name: "opencv2",
            url: "https://github.com/DanielPHP01/MergenSDK-iOS/releases/download/v2.1.0/opencv2.xcframework.zip",
            checksum: "359d556ff951388471d27e05136ba7d8ec4d10870b23e0383cf1f157e542e42d"
        ),
        .binaryTarget(
            name: "onnxruntime",
            url: "https://github.com/DanielPHP01/MergenSDK-iOS/releases/download/v2.1.0/onnxruntime.xcframework.zip",
            checksum: "9d67d66d45b6f9d75a0d00b2ba36568fcb4e89d6672515233e3dde0edd97e2b6"
        ),
        .binaryTarget(
            name: "libcrypto",
            url: "https://github.com/DanielPHP01/MergenSDK-iOS/releases/download/v2.1.0/libcrypto.xcframework.zip",
            checksum: "f7ae1bd36d75dd8ab505f09dbc3b868f519143698f9ee2c5b6dde27ec60be8ef"
        ),
        .binaryTarget(
            name: "libssl",
            url: "https://github.com/DanielPHP01/MergenSDK-iOS/releases/download/v2.1.0/libssl.xcframework.zip",
            checksum: "da5bcd65f7530270e1c7f00d8f23cb02bebd900dc39ab01da1f82e3cf44b5545"
        ),
        // Swift wrapper + Resources (models/dicts) — regular target, ships via git.
        // (binaryTarget cannot carry resources / Bundle.module — see
        // scripts/release_ios.sh Step 5 comment for the full rationale.)
        .target(
            name: "Mergen",
            dependencies: [
                "MergenCore",
                "opencv2",
                "onnxruntime",
                "libcrypto",
                "libssl",
            ],
            path: "Sources/Mergen",
            resources: [
                .copy("Resources/m12.onnx.encrypted"),
                .copy("Resources/m13.onnx.encrypted"),
                .copy("Resources/m14.onnx.encrypted"),
                .copy("Resources/m15.onnx.encrypted"),
                .copy("Resources/m4.onnx.encrypted"),
                .copy("Resources/m4_dict.txt"),
                .copy("Resources/m5.ort.encrypted"),
                .copy("Resources/m7.onnx.encrypted"),
                .copy("Resources/m7_dict.txt"),
            ],
            linkerSettings: [
                .linkedFramework("Accelerate"),
                .linkedFramework("CoreVideo"),
                .linkedFramework("CoreMedia"),
                .linkedFramework("AVFoundation"),
                .linkedLibrary("c++"),
                .linkedLibrary("opencv_merged"),
                .linkedFramework("onnxruntime"),
                .linkedLibrary("crypto"),
                .linkedLibrary("ssl"),
            ]
        ),
    ]
)
