// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "Mergen",
    platforms: [.iOS(.v15)],
    products: [
        // One-line client integration: add "Mergen" as a package dependency and this
        // product as a target dependency. Both the binary framework (Mergen) and the
        // model-asset bundle (MergenResources) are included automatically.
        .library(
            name: "Mergen",
            targets: ["Mergen", "MergenResources"]
        ),
        // Debug/QA diagnostics module. Add to QA targets only — writes PII to os_log.
        // See docs/DIAGNOSTICS.md for integration guidance.
        .library(
            name: "MergenDebugger",
            targets: ["MergenDebugger"]
        ),
    ],
    targets: [
        // Swift wrapper — precompiled binary framework (BUILD_LIBRARY_FOR_DISTRIBUTION,
        // MACH_O_TYPE=mh_dylib). Produced by ios_framework/MergenSwift.xcodeproj —
        // NOT built by this package itself (see ios_framework/, generated by a Ruby
        // `xcodeproj`-gem script; no plain Xcode-GUI project checked in).
        //
        // MergenCore (C++ static core) + opencv2 + onnxruntime + libcrypto + libssl are
        // linked STATICALLY INSIDE this dylib at archive time — they are no longer
        // separate SPM binaryTargets/dependencies here, and clients no longer need any
        // linkerSettings for them (previously: Accelerate/CoreVideo/CoreMedia/
        // AVFoundation/libc++/opencv_merged/onnxruntime/crypto/ssl — all now internal).
        // MergenCore specifically is linked via a direct OTHER_LDFLAGS path to its raw
        // per-platform archive (ios_framework's generator script), NOT as a normal
        // Frameworks-and-Libraries xcframework entry — its inner per-slice bundle is
        // ALSO literally named "Mergen.framework" (see Mergen.xcframework/ios-arm64/),
        // which collides with this target's own "Mergen.framework" product at
        // BuildProductsPath if linked the normal way ("Multiple commands produce...").
        //
        // The xcframework WRAPPER folder is named "MergenSwift.xcframework" (cosmetic —
        // avoids an on-disk name clash with the existing Mergen.xcframework, the C++
        // core), but the .framework INSIDE each platform slice, and the compiled Swift
        // module, are both literally "Mergen" (PRODUCT_NAME == PRODUCT_MODULE_NAME ==
        // "Mergen") — both must match for standard `-F` framework-search `import Mergen`
        // resolution to find it; PRODUCT_NAME alone diverging from PRODUCT_MODULE_NAME
        // (tried first) produces "error: Unable to find module dependency: 'Mergen'" in
        // every consumer.
        //
        // ✅ BLOCKER RESOLVED: The top-level façade enum was renamed from `Mergen` to
        // `MergenSDK` (Mergen.swift). The module is still "Mergen" (`import Mergen`)
        // and all other public types are unchanged. The .swiftinterface no longer contains
        // self-shadowing qualified references. Client migration: s/Mergen\.(verify|verifyCards|
        // warmUp|preload|makeScanResult)/MergenSDK.$1/g.
        .binaryTarget(
            name: "Mergen",
            path: "MergenSwift.xcframework"
        ),
        // Model asset bundle — source-only target that carries the encrypted model files
        // (m4, m5, m7, m12–m15, ~73 MB) as SPM resources. Declared alongside the binary
        // `Mergen` target in the `Mergen` product so clients get both with one dependency.
        //
        // WHY A SEPARATE TARGET:
        // xcframework slices are per-platform binaries; embedding resources inside each
        // slice duplicates them (device slice + simulator slice = 2× = ~147 MB for ~73 MB
        // of models). A source target has no per-platform duplication — SPM creates one
        // `Mergen_MergenResources.bundle` placed in the app bundle root.
        //
        // HOW THE BINARY FINDS RESOURCES:
        // `MergenEngine.findResourceBundle()` (in MergenEngine.swift) searches
        // Bundle.allBundles, then named companion bundles in Bundle.main, then falls
        // back to the framework bundle for backward-compat with pre-split xcframeworks.
        // Clients can also call `MergenEngine.setResourceBundle(_:)` explicitly.
        .target(
            name: "MergenResources",
            path: "Sources/MergenResources",
            resources: [
                .copy("m4.onnx.encrypted"),
                .copy("m4_dict.txt"),
                .copy("m5.ort.encrypted"),
                .copy("m7.onnx.encrypted"),
                .copy("m7_dict.txt"),
                .copy("m12.onnx.encrypted"),
                .copy("m13.onnx.encrypted"),
                .copy("m14.onnx.encrypted"),
                .copy("m15.onnx.encrypted"),
            ]
        ),
        // Debug/QA module — PII diagnostics implementation (source; no algorithms —
        // logging/formatting only). Dependency is ONE-WAY: MergenDebugger → Mergen.
        // Never the reverse. Clients: add to a separate QA Xcode target.
        // See docs/DIAGNOSTICS.md.
        .target(
            name: "MergenDebugger",
            dependencies: ["Mergen"],
            path: "Sources/MergenDebugger"
        ),
    ]
)
